[[keys.normal]]
key = "C-a"
action = "goto_line_start"

[[keys.normal]]
key = "C-e"
action = "goto_line_end"
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]

[[keys.insert]]
key = "C-a"
action = "goto_line_start"

[[keys.insert]]
key = "C-e"
action = "goto_line_end"

[[keys.select]]
key = "C-a"
action = "goto_line_start"
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

